### ISSUE TITLE
Feature Selection Module

### ISSUE THREAD

**Issue by liwenjielongren** [Anymake/DRN_CVPR2020#10]
大家有人跑了这个模块吗，我遇到一个问题AttributeError: 'NoneType' object has no attribute 'data'，应该是反向传播时梯度更新的问题，请问怎样解决。

**Comment by Panxjia** [comment]
能把问题描述的更加详细些吗，比如使用模块的代码，以及出错的日志，目前只有这个信息，我没办法判断是哪出的问题

**Comment by liwenjielongren** [comment]
你好，我找到问题了，是我自己分布式训练的问题。模块没有问题
