### ISSUE TITLE
已放出的这部分代码与论文中是否存在一定出入？

### ISSUE THREAD

**Issue by KKKiven** [Anymake/DRN_CVPR2020#13]
代码中在FSM模块中的attention map似乎与论文中有一定出入？论文中的attention map Ai维度是H*W*1，并且是在得到attention map后再concat+softmax; 而代码中先将三个分支相加，然后通过AdaptiveAvgPool2d使attention map的H和W维度均变为了1（这样看的话似乎论文中是空间注意力而代码中是通道注意力？）。不知我的理解是否有误？

**Comment by Panxjia** [comment]
嗯嗯，对的。 代码里两个都有，空间注意力的版本在上面注释掉了。

**Comment by KKKiven** [comment]
啊啊，我的错，没注意到注释的部分~



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Panxjia <notifications@github.com&gt;
发送时间: 2020年11月9日 22:08
收件人: Anymake/DRN_CVPR2020 <DRN_CVPR2020@noreply.github.com&gt;
抄送: KKKiven <1743756161@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Anymake/DRN_CVPR2020] 已放出的这部分代码与论文中是否存在一定出入？ (#13)





 
嗯嗯，对的。 代码里两个都有，空间注意力的版本在上面注释掉了。
